CREATE TABLE alarms (
    uuid CHAR(36) PRIMARY KEY,
    channel_uuid CHAR(36),
    business_uuid CHAR(36),
    table_name VARCHAR(255),
    column_name VARCHAR(255),
    name VARCHAR(255),
    description TEXT,
    time_range INTEGER,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by CHAR(36),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by CHAR(36),
    condition_logic VARCHAR(255),
    condition_show VARCHAR(255),
    triggered BOOLEAN DEFAULT false,
    alarm_type VARCHAR(255),
    var01 INTEGER,
    var02 INTEGER,
    var03 INTEGER,
    var04 INTEGER,
    var05 INTEGER,
    var06 INTEGER,
    FOREIGN KEY (channel_uuid) REFERENCES channels(uuid) ON DELETE CASCADE,
    FOREIGN KEY (business_uuid) REFERENCES businesses(uuid) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(uuid),
    FOREIGN KEY (updated_by) REFERENCES users(uuid)
);
