@api = http://localhost:5000/api

@business_uuid = 4e329ada-8511-4bfa-8d44-57a0ca4fd80c

# Login as Owner
# dni: 28470359 password: Pass1234
# @name login_owner
POST {{api}}/auth/login
Content-Type: application/json

{
  "dni": "28470359",
  "password": "Pass1234"
}


###
@token = {{login_owner.response.body.token}}
@business_user_owner = {{login_owner.response.body.user.businesses_roles[0].uuid}}

###
# Get all channels
GET {{api}}/businesses/{{business_user_owner}}/channels
Authorization: Bearer {{token}}

###
# Create a new channel
POST {{api}}/businesses/{{business_uuid}}/channels
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "New Channel",
  "description": "A new channel for testing",
  "datalogger_id": "eefa9754-1c0f-41a6-9dfb-e2d37bb52245",
  "column_name": "test_col",
  "averaging_period": 30,
  "factor": 2.5,
  "img": "http://example.com/channel3.jpg"
}

###
# Get a channel by UUID
GET {{api}}/businesses/{{business_user_owner}}/channels/65646362-6160-5958-5756-555453525150
Authorization: Bearer {{token}}

###
# Update a channel
PUT {{api}}/businesses/{{business_user_owner}}/channels/65646362-6160-5958-5756-555453525150
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Updated Temperature"
}

###
# Soft delete a channel
DELETE {{api}}/businesses/{{business_user_owner}}/channels/65646362-6160-5958-5756-555453525150
Authorization: Bearer {{token}}

###
# Hard delete a channel
DELETE {{api}}/businesses/{{business_user_owner}}/channels/65646362-6160-5958-5756-555453525150/hard
Authorization: Bearer {{token}}
