@api = http://localhost:5000/api

//@api = https://mdv-monitoreo-remoto-backend.onrender.com/api
@token = 

###
# Owner User Tests
# This file tests all actions for a user with the 'Owner' role.
# An Owner should be able to perform all actions on all users and businesses.
###

# Login as Owner
# dni: 28470359 password: Pass1234
# @name login_owner
POST {{api}}/auth/login
Content-Type: application/json

{
  "dni": "28470359",
  "password": "Pass1234"
}

### Login as Admin
# dni: 11111112 password: Pass1234
# @name login_admin
POST {{api}}/auth/login
Content-Type: application/json

{
  "dni": "11111112",
  "password": "Pass1234"
}


###
@token = {{login_owner.response.body.token}}
@own_business_uuid = {{login_owner.response.body.user.businesses_roles[0].uuid}}

@datalogger_quilmes = h3d4e5f6-a7b8-9012-3456-7890abcdef12

@datalogger_mdv = g2c3d4e5-f6a7-8901-2345-67890abcdef1

@channel_cafetera = 25242322-2120-1918-1716-151413121110

@channel_dispenser = 65646362-6160-5958-5756-555453525150

@channel_compresor1_guemes = 30313233-3435-3637-3839-404142434445

@channel_compresor1_quilmes = a0a1a2a3-a4a5-a6a7-a8a9-b0b1b2b3b4b5

@channel_compresor2_quilmes = b5b4b3b2-b1b0-a9a8-a7a6-a5a4a3a2a1a0


### /data/
GET {{api}}/data/getLastPorcentageUsageByChannel/businesses/{{own_business_uuid}}/{{datalogger_mdv}}/{{channel_dispenser}}
Content-Type: application/json
Authorization: Bearer {{token}}

### /data/getDataloggerLastData/:dataloggerUuid 
GET {{api}}/data/getDataloggerLastData/businesses/{{own_business_uuid}}/{{datalogger_quilmes}}
Content-Type: application/json
Authorization: Bearer {{token}}

### '/data/allregisters/:channeluuid' 
# required filter queries: 'start' and 'end'. Example: ?start='2025-12-01'&end='2025-12-31'

GET {{api}}/data/allregisters/businesses/{{own_business_uuid}}/{{channel_compresor1_quilmes}}?start='2026-01-12T00:00:00'&end='2026-01-12T18:14:00'
Content-Type: application/json
Authorization: Bearer {{token}}

### '/data/alldaily/:channeluuid' 
# required filter queries: 'start' and 'end'. Example: ?start='2025-12-01'&end='2025-12-31'

GET {{api}}/data/alldaily/businesses/{{own_business_uuid}}/{{channel_compresor1_quilmes}}?start='2025-06-01'&end='2025-12-31'
Content-Type: application/json
Authorization: Bearer {{token}}

### '/data/allweekly/:channeluuid' 
# required filter queries: 'start' and 'end'. Example: ?start='2025-12-01'&end='2025-12-31'

GET {{api}}/data/allweekly/businesses/{{own_business_uuid}}/{{channel_compresor1_quilmes}}?start='2025-06-01'&end='2026-01-06'
Content-Type: application/json
Authorization: Bearer {{token}}

### '/data/totalontime/:channeluuid'
# required filter queries: 'start' and 'end'. Example: ?start='2025-12-01'&end='2025-12-31'

GET {{api}}/data/totalontime/businesses/{{own_business_uuid}}/{{channel_compresor1_quilmes}}?start='2025-06-01'&end='2025-12-31'
Content-Type: application/json
Authorization: Bearer {{token}}

### '/data/energyincidents/:dataloggerUuid'
# required filter queries: 'start' and 'end'. Example: ?start='2025-06-01'&end='2025-12-31'
# Devuelve cortes de energia (energia=1) y reinicios (texto='Iniciando equipo')

GET {{api}}/data/energyincidents/businesses/{{own_business_uuid}}/{{datalogger_quilmes}}?start='2025-06-01'&end='2025-12-31'
Content-Type: application/json
Authorization: Bearer {{token}}

### '/data/energyincidents/:dataloggerUuid' - Rango corto
# Prueba con un rango de fechas mas corto

GET {{api}}/data/energyincidents/businesses/{{own_business_uuid}}/{{datalogger_quilmes}}?start='2026-01-15'&end='2026-04-15'
Content-Type: application/json
Authorization: Bearer {{token}}

### '/data/energyincidents/:dataloggerUuid' - Sin params (deberia dar error 400)
GET {{api}}/data/energyincidents/businesses/{{own_business_uuid}}/{{datalogger_mdv}}
Content-Type: application/json
Authorization: Bearer {{token}}