@api = http://localhost:5000/api
@admin_email = john.doe@example.com
@admin_password = password123
@token = 

###
# @name login
POST {{api}}/auth/login
Content-Type: application/json

{
  "dni": "28470359",
  "password": "Pass1234"
}

###
@token = {{login.response.body.token}}

###
@business_uuid = {{login.response.body.user.businesses_roles[0].uuid}}

###
@user_uuid = {{login.response.body.user.uuid}}

###
# Get all solutions
GET {{api}}/businesses/{{business_uuid}}/solutions
Authorization: Bearer {{token}}

###
# Create a new solution
POST {{api}}/businesses/{{business_uuid}}/solutions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "New Solution",
  "description": "A new solution for testing",
  "alarms_logs_id": "81625590-d9fa-457e-b6fb-1194c45aa37d", 
  "user_id": "{{user_uuid}}",
  "business_uuid": "4e329ada-8511-4bfa-8d44-57a0ca4fd80c"
}


###
# Get a solution by UUID
GET {{api}}/businesses/6a541cec-0733-4dfc-8f66-79c2ec6bf02e/solutions/e5f6a7b8-c9d0-1234-5678-90abcdef1234
Authorization: Bearer {{token}}

### Get solutions by alarms_logs_id
GET {{api}}/businesses/4e329ada-8511-4bfa-8d44-57a0ca4fd80c/solutions/alarmlogs/81625590-d9fa-457e-b6fb-1194c45aa37d
Authorization: Bearer {{token}}

###
# Update a solution
PUT {{api}}/businesses/{{business_uuid}}/solutions/e5f6a7b8-c9d0-1234-5678-90abcdef1234
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "description": "Updated Solution for weather alerts"
}

###
# Soft delete a solution - NOT WORKING YET 18 DEC 2025
DELETE {{api}}/businesses/{{business_uuid}}/solutions/708dead5-7bf5-4fb6-8d64-533afd8f67e3
Authorization: Bearer {{token}}

###
# Hard delete a solution - NOT WORKING YET 18 DEC 2025
DELETE {{api}}/businesses/{{business_uuid}}/solutions/f6a7b8c9-d0e1-2345-6789-0abcdef12345/hard
Authorization: Bearer {{token}}
