@api = http://localhost:5000/api
@admin_email = john.doe@example.com
@admin_password = password123
@token = 

###
# @name login
POST {{api}}/auth/login
Content-Type: application/json

{
  "dni": "28470359",
  "password": "Pass1234"
}

###
@token = {{login.response.body.token}}

###
@business_uuid = {{login.response.body.user.businesses_roles[0].uuid}}

###
@user_uuid = {{login.response.body.user.uuid}}

###
# Get all solutions
GET {{api}}/businesses/{{business_uuid}}/solutions
Authorization: Bearer {{token}}

###
# Create a new solution
POST {{api}}/businesses/{{business_uuid}}/solutions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "New Solution",
  "description": "A new solution for testing",
  "business_uuid": "{{business_uuid}}",
  "event_uuid": "81625590-d9fa-457e-b6fb-1194c45aa37d", 
  "user_id": "{{user_uuid}}" 
}


###
# Get a solution by UUID
GET {{api}}/businesses/{{business_uuid}}/solutions/9ef1f276-063b-4c95-a6de-af35d9ea5413
Authorization: Bearer {{token}}

### Get solutions by alarms_logs_id

GET {{api}}/businesses/{{business_uuid}}/solutions/alarmlogs/3b516834-039c-4433-8a39-c5c9e4224c30
Authorization: Bearer {{token}}

###
# Update a solution
PUT {{api}}/businesses/{{business_uuid}}/solutions/9ef1f276-063b-4c95-a6de-af35d9ea5413
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "description": "Updated Solution for weather alerts"
}

###
# Soft delete a solution - NOT WORKING YET 18 DEC 2025
DELETE {{api}}/businesses/{{business_uuid}}/solutions/9ef1f276-063b-4c95-a6de-af35d9ea5413
Authorization: Bearer {{token}}

###
# Hard delete a solution -  WORKING 9 ENE 2026
DELETE {{api}}/businesses/{{business_uuid}}/solutions/9ef1f276-063b-4c95-a6de-af35d9ea5413/hard
Authorization: Bearer {{token}}
