@api = http://localhost:5000/api
@business_mdvsrl = 4e329ada-8511-4bfa-8d44-57a0ca4fd80c
@business_guemes = 2b3c4d5e-6f7a-4b8c-9d0e-1f2a3b4c5d6e

@alarm_compresor2_guemes = a1b2c3d4-0003-4a7b-8c9d-0e1f2a3b4c5d

@alarm_cafetera_mdvsrl = b1c2d3e4-0001-4a7b-8c9d-0e1f2a3b4c5d

@user_fernando_quilmes = 9c0d1e2f-3a4b-5c6d-7e8f-90a1b2c3d4e5

@user_juan_carlos_fernandez = e1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d

@user_norberto = 4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f90

###
# Owner Login (Juan Carlos Fernandez)
# @name ownerLogin
POST {{api}}/auth/login
Content-Type: application/json

{
  "dni": "28470359",
  "password": "Pass1234"
}

###
# Admin Login (Jane Smith)
# @name adminLogin
POST {{api}}/auth/login
Content-Type: application/json

{
  "dni": "28470361",
  "password": "Password1234"
}

###
# Technician Login (Mike Matei)
# @name technicianLogin
POST {{api}}/auth/login
Content-Type: application/json

{
  "dni": "28470350",
  "password": "1298"
}

###  /businesses/:businessUuid/alarms/user/:userId
# Get all alarms as Owner by user id - from another route, but it is needed to test the association between users and alarms.
GET {{api}}/businesses/{{business_mdvsrl}}/alarms/user/{{user_norberto}}
Authorization: Bearer {{ownerLogin.response.body.token}}

### /businesses/:businessUuid/users-alarms
# Create a new users-alarms. Its associates an alarm to a user.
POST {{api}}/businesses/{{business_guemes}}/users-alarms
Authorization: Bearer {{ownerLogin.response.body.token}}
Content-Type: application/json

{
  "alarm_uuid": "{{alarm_compresor2_guemes}}",
  "user_uuid": "{{user_norberto}}",  
  "business_uuid": "{{business_mdvsrl}}"
}

###
# '/businesses/:businessUuid/users-alarms/alarm/:alarmUuid'
GET {{api}}/businesses/{{business_guemes}}/users-alarms/alarm/{{alarm_cafetera_mdvsrl}}
Authorization: Bearer {{ownerLogin.response.body.token}}


###
# Update an alarm as Owner
PUT {{api}}/alarms/{{business_mdvsrl}}
Authorization: Bearer {{ownerLogin.response.body.token}}
Content-Type: application/json

{
    "name": "Updated High Temperature Alert"
}

### '/businesses/:businessUuid/users-alarms/:uuid/hard'
# Delete an alarm as Owner
DELETE {{api}}/businesses/{{business_mdvsrl}}/users-alarms/c710e365-cff0-42c2-8a0b-ef54d288687d/hard
Authorization: Bearer {{ownerLogin.response.body.token}}


###
# Create a new alarm as Admin
POST {{api}}/alarms
Authorization: Bearer {{adminLogin.response.body.token}}
Content-Type: application/json

{
    "channel_uuid": "a1b2c3d4-e5f6-a7b8-c9d0-e1f2a3b4c5d6",
    "name": "Admin Test Alarm",
    "description": "A test alarm created by the admin.",
    "time_range": 600,
    "condition_logic": "value < 10",
    "condition_show": "Value < 10",
    "alarm_type": "lower_threshold",
    "var01": 10
}
